name: memechat
description: A new flutter project.

dependencies:
  flutter:
    sdk: flutter
  image_picker:
    git: git://github.com/flutter/image_picker
  google_sign_in:
    git: git://github.com/flutter/google_sign_in
  firebase_auth:
    git: git://github.com/flutter/firebase_auth
  firebase_database:
    git: git://github.com/flutter/firebase_database
  firebase_storage:
    git: git://github.com/flutter/firebase_storage

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the Icons class.
  uses-material-design: true

  fonts:
    - family: Impact
      fonts:
        - asset: assets/fonts/Impact.ttf
  # To add assets to your application, add an assets section here, in
  # this "flutter" section, as in:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
